#!/usr/bin/env ruby
require './pluralize'

def start time, activity
  `notify-send -t #{time} "Starting work on #{activity}" "#{"minute".pluralize(time)} left"`
end

def end activity
end

def loop! time
  time.times do |index|
    `sleep 60`
    puts "You've worked #{"minute".pluralize(index + 1)} out of #{time}"
  end
end

def finish_up activity
  `notify-send "Finish up #{activity}" "Time's up"`
  puts "Time is up"
  `aplay -q bell.wav`
end

@activity = ARGV[0] || "pomodoro"
@time = (ARGV[1] || 30).to_i

start @time, @activity
loop! @time
finish_up @activity
